color0 #45474c
color1 #ffb4ab
color2 #bfc7d9
color3 #c4c6ce
color4 #cfc2d6
color5 #bfc7d9
color6 #c4c6ce
color7 #e4e2e3
color8 #8f9096
color9 #ffb4ab
color10 #bfc7d9
color11 #c4c6ce
color12 #cfc2d6
color13 #bfc7d9
color14 #c4c6ce
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c5c6cc
selection_background  #45474c
active_border_color   #bfc7d9
inactive_border_color #45474c
url_color             #bfc7d9

active_tab_foreground   #29313f
active_tab_background   #bfc7d9
inactive_tab_foreground #c5c6cc
inactive_tab_background #45474c
cursor_trail_color      #c5c6cc
